name: device_geometry
description: "Flutter package providing information about the device geometry, such as the corner radius."
version: 0.0.1
homepage: https://github.com/bcheidemann/flutter_device_geometry

environment:
  sdk: ^3.9.0
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  device_info_plus: ^12.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
